// Renders a branded 1200x630 cover for every seeded blog post into
// public/images/blog/covers and rewrites lib/data/blog-covers.ts.
// Run: npm run blog:covers
import { mkdir, readFile, writeFile } from 'node:fs/promises'
import path from 'node:path'
import sharp from 'sharp'
import { ImageResponse } from 'next/og'
import { seedPosts } from '../prisma/blog-seed'
import {
  COVER_BACKGROUND,
  COVER_HEIGHT,
  COVER_WIDTH,
  blogCoverPath,
  coverAccent,
  coverLabelSize,
  coverRings,
  hexToRgb,
} from '../lib/blog-cover'

const root = process.cwd()
const outDir = path.join(root, 'public', 'images', 'blog', 'covers')
const muted = '#A8A8A4'

function Cover({ slug, category }: { slug: string; category: string }) {
  const rings = coverRings(slug)
  const accent = coverAccent(category)
  const [r, g, b] = hexToRgb(accent)
  return (
    <div
      style={{
        width: '100%',
        height: '100%',
        display: 'flex',
        position: 'relative',
        background: COVER_BACKGROUND,
        color: '#FFFFFF',
        fontFamily: 'Brasika',
      }}
    >
      {rings.map((ring, i) => (
        <div
          key={i}
          style={{
            position: 'absolute',
            left: ring.cx - ring.r,
            top: ring.cy - ring.r,
            width: ring.r * 2,
            height: ring.r * 2,
            borderRadius: ring.r,
            border: `2px solid rgba(${r}, ${g}, ${b}, ${0.08 + (i % 3) * 0.04})`,
          }}
        />
      ))}
      <div
        style={{
          display: 'flex',
          flexDirection: 'column',
          justifyContent: 'space-between',
          width: '100%',
          height: '100%',
          padding: '64px 72px',
        }}
      >
        <div style={{ display: 'flex', fontSize: 26, letterSpacing: 6, color: muted }}>INFLUENCER MARKETING</div>
        <div
          style={{
            display: 'flex',
            maxWidth: 1000,
            fontSize: coverLabelSize(category),
            lineHeight: 1.05,
            letterSpacing: -2,
            color: accent,
          }}
        >
          {category}
        </div>
        <div
          style={{
            display: 'flex',
            justifyContent: 'space-between',
            alignItems: 'center',
            fontSize: 26,
            color: muted,
          }}
        >
          <div style={{ display: 'flex', color: '#FFFFFF', letterSpacing: 4 }}>CA AGENCY</div>
          <div style={{ display: 'flex' }}>caagency.com/blog</div>
        </div>
      </div>
    </div>
  )
}

async function main() {
  const font = await readFile(path.join(root, 'public', 'fonts', 'BrasikaDisplay.ttf'))
  await mkdir(outDir, { recursive: true })

  const slugs: string[] = []
  for (const post of seedPosts) {
    const category = post.categories[0] ?? 'Insights'
    const png = await new ImageResponse(<Cover slug={post.slug} category={category} />, {
      width: COVER_WIDTH,
      height: COVER_HEIGHT,
      fonts: [{ name: 'Brasika', data: font, style: 'normal', weight: 400 }],
    }).arrayBuffer()
    await sharp(Buffer.from(png)).webp({ quality: 88 }).toFile(path.join(root, 'public', blogCoverPath(post.slug)))
    slugs.push(post.slug)
    console.log(`Cover: ${post.slug}`)
  }

  const manifest = `// Generated by scripts/generate-blog-covers.tsx. Do not edit by hand.
export const generatedCoverSlugs: ReadonlySet<string> = new Set([
${slugs.map((slug) => `  '${slug}',`).join('\n')}
])
`
  await writeFile(path.join(root, 'lib', 'data', 'blog-covers.ts'), manifest)
}

main().catch((error) => {
  console.error('Cover generation failed:', error)
  process.exit(1)
})
